# NLP

## Лабораторная 1

### Регулярные выражения

Полезные ссылки: https://habr.com/ru/articles/349860/
        

Шпаргалка по регулярным выражения

\. - любой символ

\d или [0-9] - любой цифровой символ

\D или [^0-9] - любой не цифровой символ

\s или [ \f\n\r\t\v] - пробельный символ

\S или [^ \f\n\r\t\v] - не пробельный символ

\w или [A-Za-z0-9_] - буквенный, цифровой или знак подчеркивания

\W или [^A-Za-z0-9_] - любой кроме буквенного, цифрового и знака подчеркивания

? или {0, 1} - предыдущий символ может встречаться ноль или один раз

\* или {0, } - предыдущий символ может встречаться ноль и более раз

\+ или {1, } - предыдущий символ может встреться один или более раз

{n} - предыдущий символ встречается ровно n раз

{m, n} - предыдущий символ встречается от n до m раз

{m, } -предыдущий символ встречается не менее m раз

{, n} - предыдущий символ встреччается не более n раз

Жадный оператор выбирает максимально длинную подстроку из возможных

Ленивый оператор выбирает максимально короткую подстроку из возможных

жадные операторы:

\*

\+

{n, }

ленивые операторы:

\*?

\+?

{n, }?

| - или

[ ] - диапазон

Список служебных символов (необходимо экранировать): [, ], \\, |\, /\, ^, $, ., ?, \*, \+, (, ),{, }

In [1]:
import re
import pandas as pd
from typing import List

In [2]:
example = """
Необходимо найти в тексте все аббревиатуры. Вот первая АСУ.
Вот вторая ГЭС. Аббревиатуры могут быть на английском языке например PHP и SMART.
"""

s = re.findall("[A-ZА-ЯЁ]+[^ \.a-zа-яё]", example)
print(s)

['АСУ', 'ГЭС', 'PHP', 'SMART']

In [3]:
text='''В июне 2022 года компания объявила о решении вдохнуть новую жизнь в ya.ru - еще до официального анонса об обмене активов между "Яндексом" и VK. Тогда в компании объясняли, что ya.ru станет "одной из точек входа с фокусом на универсальный поиск, специализированные поисковые вертикали и Алису".

В августе, когда стало известно о сделке между компаниями, в рамках которой VK стал владельцем новостного агрегатора и "Дзена", "Яндекс" заявил о решении сменить главную страницу сайта впервые в истории после совершения сделки, сделав основной страницей тот самый альтернативный вариант - ya.ru.

Теперь прежняя основная страница с новостным агрегатором и порталом "Дзен" перешла во владение VK, с 12 сентября при обращении на yandex.ru совершается переадресация на dzen.ru - домен, принадлежащий VK. Тем не менее, домен yandex.ru остается в собственности "Яндекса" - yandex.ru доступен для просмотра страницы о компании, правовых документов и большинства сервисов.

"Яндекс" за последние годы существенно диверсифицировал бизнес-модель, однако рекламные доходы, куда включен поисковый сервис, остаются ключевой составляющей выручки: во II квартале этот показатель составил 48,4 млрд рублей, или 40% от консолидированной выручки. На российском рынке поиска "Яндекс" конкурирует с глобальным игроком - Google.

По данным аналитической системы "Яндекс Радар", в период с 29 августа по 4 сентября доля "Яндекса" на поисковом рынке России составила 62,26%, в то время как у Google - 36,38%. На мобильных устройствах доля российской компании за указанный период находилась на уровне 58,35%, у американской - 40,76%.

"Мы не ожидаем снижения поисковой доли "Яндекса", - заявил представитель компании. Аналитики "Велес Капитала" и Альфа-банка в настоящее время также не видят условий, при которых доля "Яндекса" на рынке могла бы снизиться.

"Десктоп обеспечивает только 1/3 всех запросов в "Яндексе", более 60% приходит с мобильных устройств и важнее, что происходит там. Также сервисы компании остаются завязаны на собственном поиске и с них трафик идет именно "Яндексу". "Новости" и "Дзен" сами по себе являлись важными генераторами дополнительного трафика и привлекали людей на основную страницу. Когда они станут полностью отдельными и не будут иметь ссылок на поиск Яндекса - это может несколько снизить число ежедневных обращений", - считают в "Велес Капитале".

Представитель "Яндекса" сообщил "Интерфаксу, что компания видит рост аудитории на ya.ru с момента его обновления. Абсолютные цифры в компании не раскрыли, впрочем, как и маркетинговые планы по привлечению новых пользователей на страницу. Также в компании пока не комментируют судьбу сайта yandex.ru после завершения переходного периода.

С точки зрения финансового положения компания не должна испытать влияния на доходы от рекламной выручки. Несмотря на то, что на сайте dzen.ru есть поисковая строка "Яндекса", пользователи после ввода запроса оказываются в поисковой выдаче сайта yandex.ru, на которой уже и происходит монетизация.

Одновременно с этим представитель компании допустил, что продажа "Новостей" и "Дзена" может отрицательно сказаться на финансовых результатах "Яндекса" на краткосрочном горизонте. "Конечно, продажа "Новостей" и "Дзена" может негативно повлиять на наши финансовые показатели в краткосрочной перспективе. Но мы уверены, что в будущем эта сделка позволит стать компании еще устойчивее", - отметил он.

Согласно презентации "Яндекса", в IV квартале 2021 прогнозный показатель по выручке "Дзена", который относился к экспериментальному направлению компании, составлял 18,9 млрд рублей. Финпоказатели "Новостей" (входили в направление "Поиск и Портал") "Яндекс" не раскрывал.

Пользовательский опыт
В настоящее время сайт dzen.ru старается сохранить максимально знакомый интерфейс для пользователей, привыкших пользоваться старой главной страницей "Яндекса", утверждают представители двух компаний.

В действительности, принадлежащий VK сайт сейчас содержит поисковую строку и сервис "Погода" своего конкурента на рынке, другие его продукты, например, "Кинопоиск" или "Почта", отображаются лишь при нажатии на строку поиска, а переход на них осуществляется через открытие сайтов, принадлежащих "Яндексу".

"Часть людей изначально заходили на yandex.ru ради поиска. Нам важно сохранить пользовательский опыт. Поэтому пока мы планируем сохранить ее. Также там останется Яндекс ID", - объяснил "Интерфаксу" представитель "Яндекса".

Представитель VK сообщил, у компании есть планы по работе над функциональностью dzen.ru, но не конкретизировал их. При этом в пресс-службе компании отметили, что в ближайшее время "Дзен" не будет интегрироваться с "Одноклассниками" и "ВКонтакте" - другими соцсетями, принадлежащими компании. Эти сервисы также развивают направление медиа и взаимодействуют с блогерами.

Ряд пользователей с учетной записью "Яндекса" обратили внимание на то, что их авторизация через "Яндекс ID" сохраняется на сайте dzen.ru, не требуя ввода пароля. Отвечая на вопрос о безопасности персональных данных пользователей, пресс-служба "Яндекса" уточнила, что через "Яндекс ID" можно авторизоваться на многих сторонних сайтах, однако данные не передаются третьим сторонах, несмотря на возможность входа на сайт без ввода учетных данных.

"Портал dzen.ru может получить идентификатор, который помогает ему узнать пользователя и показать ему подписки, лайки и комментарии, чтобы все рекомендации продолжили работать как ранее. Никакие другие данные пользователей Яндекса не передаются", - пояснили в компании.'''

In [4]:
##Найдите в text все слова начинающиеся с заглавной буквы (включая иностранные) при помощи функции findall
ans = re.findall("[A-ZА-ЯЁ]{1}[a-zа-яё]+", text)

ans

['Яндексом',
 'Тогда',
 'Алису',
 'Дзена',
 'Яндекс',
 'Теперь',
 'Дзен',
 'Тем',
 'Яндекса',
 'Яндекс',
 'На',
 'Яндекс',
 'Google',
 'По',
 'Яндекс',
 'Радар',
 'Яндекса',
 'России',
 'Google',
 'На',
 'Мы',
 'Яндекса',
 'Аналитики',
 'Велес',
 'Капитала',
 'Альфа',
 'Яндекса',
 'Десктоп',
 'Яндексе',
 'Также',
 'Яндексу',
 'Новости',
 'Дзен',
 'Когда',
 'Яндекса',
 'Велес',
 'Капитале',
 'Представитель',
 'Яндекса',
 'Интерфаксу',
 'Абсолютные',
 'Также',
 'Несмотря',
 'Яндекса',
 'Одновременно',
 'Новостей',
 'Дзена',
 'Яндекса',
 'Конечно',
 'Новостей',
 'Дзена',
 'Но',
 'Согласно',
 'Яндекса',
 'Дзена',
 'Финпоказатели',
 'Новостей',
 'Поиск',
 'Портал',
 'Яндекс',
 'Пользовательский',
 'Яндекса',
 'Погода',
 'Кинопоиск',
 'Почта',
 'Яндексу',
 'Часть',
 'Нам',
 'Поэтому',
 'Также',
 'Яндекс',
 'Интерфаксу',
 'Яндекса',
 'Представитель',
 'При',
 'Дзен',
 'Одноклассниками',
 'Контакте',
 'Эти',
 'Ряд',
 'Яндекса',
 'Яндекс',
 'Отвечая',
 'Яндекса',
 'Яндекс',
 'Портал',
 'Никакие',
 'Яндекса']

In [6]:
text1 = '''
С помощью реглуряных выражений удобно искать номера телефонов в тексте. Все по разному записывают мобильные номера телефонов, вот несколько вариантов:
+79999999999, 89888888888, +7-917-999-99-99, 8(918)7777777. Попробуйте написать такое регулярное выражение, которое выделит все мобильные номера из текста.
И при этом не вывести номера из списка: +79126472, 25-129, 911-172-17-12.

'''

### Tокенизация

In [7]:
# 1
tokens = text1.split(',')
tokens

['\nС помощью реглуряных выражений удобно искать номера телефонов в тексте. Все по разному записывают мобильные номера телефонов',
 ' вот несколько вариантов:\n+79999999999',
 ' 89888888888',
 ' +7-917-999-99-99',
 ' 8(918)7777777. Попробуйте написать такое регулярное выражение',
 ' которое выделит все мобильные номера из текста.\nИ при этом не вывести номера из списка: +79126472',
 ' 25-129',
 ' 911-172-17-12.\n\n']

In [8]:
# 2
tokens = re.findall("[А-ЯЁа-яё]+", text1)
print(tokens)

['С', 'помощью', 'реглуряных', 'выражений', 'удобно', 'искать', 'номера', 'телефонов', 'в', 'тексте', 'Все', 'по', 'разному', 'записывают', 'мобильные', 'номера', 'телефонов', 'вот', 'несколько', 'вариантов', 'Попробуйте', 'написать', 'такое', 'регулярное', 'выражение', 'которое', 'выделит', 'все', 'мобильные', 'номера', 'из', 'текста', 'И', 'при', 'этом', 'не', 'вывести', 'номера', 'из', 'списка']

In [9]:
# 3

import nltk
# разбиение текста по пробелам и пунктуации
tokens = nltk.tokenize.word_tokenize(text1)
print(tokens)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\feature_extraction\image.py:167: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype=np.int):
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\least_angle.py:30: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  method='lar', copy_X=True, eps=np.finfo(np.float).eps,
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\least_angle.py:167: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  method='lar', copy_X=True, eps=np.finfo(np.float).eps,
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\least_angle.py:284: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  eps=np.finfo(np.float).eps, copy_Gram=True, verbose=0,
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\least_angle.py:862: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  eps=np.finfo(np.float).eps, copy_X=True, fit_path=True,
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\least_angle.py:1101: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  eps=np.finfo(np.float).eps, copy_X=True, fit_path=True,
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\least_angle.py:1127: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  eps=np.finfo(np.float).eps, positive=False):
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\least_angle.py:1362: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  max_n_alphas=1000, n_jobs=None, eps=np.finfo(np.float).eps,
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\least_angle.py:1602: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  max_n_alphas=1000, n_jobs=None, eps=np.finfo(np.float).eps,
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\least_angle.py:1738: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  eps=np.finfo(np.float).eps, copy_X=True, positive=False):

['С', 'помощью', 'реглуряных', 'выражений', 'удобно', 'искать', 'номера', 'телефонов', 'в', 'тексте', '.', 'Все', 'по', 'разному', 'записывают', 'мобильные', 'номера', 'телефонов', ',', 'вот', 'несколько', 'вариантов', ':', '+79999999999', ',', '89888888888', ',', '+7-917-999-99-99', ',', '8', '(', '918', ')', '7777777', '.', 'Попробуйте', 'написать', 'такое', 'регулярное', 'выражение', ',', 'которое', 'выделит', 'все', 'мобильные', 'номера', 'из', 'текста', '.', 'И', 'при', 'этом', 'не', 'вывести', 'номера', 'из', 'списка', ':', '+79126472', ',', '25-129', ',', '911-172-17-12', '.']

In [10]:
tokens = nltk.tokenize.sent_tokenize(text1)
print(tokens[1])

Все по разному записывают мобильные номера телефонов, вот несколько вариантов:
+79999999999, 89888888888, +7-917-999-99-99, 8(918)7777777.

In [11]:
# n-gram
# https://wiki.loginom.ru/articles/n-gramm.html
sentence = 'this is a foo bar sentences and I want to ngramize it'

n = 6
sixgrams = nltk.ngrams(sentence.split(), n)

for grams in sixgrams:
    print(grams)

('this', 'is', 'a', 'foo', 'bar', 'sentences')
('is', 'a', 'foo', 'bar', 'sentences', 'and')
('a', 'foo', 'bar', 'sentences', 'and', 'I')
('foo', 'bar', 'sentences', 'and', 'I', 'want')
('bar', 'sentences', 'and', 'I', 'want', 'to')
('sentences', 'and', 'I', 'want', 'to', 'ngramize')
('and', 'I', 'want', 'to', 'ngramize', 'it')

### Лемматизация и стемминг

In [12]:
from nltk.stem import PorterStemmer, WordNetLemmatizer
# nltk.download('wordnet')

def compare_stemmer_and_lemmatizer(stemmer, lemmatizer, word):
    """
    Print the results of stemmind and lemmitization using the passed stemmer, lemmatizer, word and pos (part of speech)
    """
    print("Stemmer:", stemmer.stem(word))
    print("Lemmatizer:", lemmatizer.lemmatize(word, pos='v'))
    print()

lemmatizer = WordNetLemmatizer()
stemmer = PorterStemmer()
compare_stemmer_and_lemmatizer(stemmer, lemmatizer, word = "seen")
compare_stemmer_and_lemmatizer(stemmer, lemmatizer, word = "drove")

Stemmer: seen
Lemmatizer: see

Stemmer: drove
Lemmatizer: drive

### Удаление стоп-слов

In [16]:
# функция удаляет стоп слова
def delete_stopwords(texts: List[List[str]], stop_words: List[str]) -> List[List[str]]:
    result = []
    for words in texts:
        clear_words = []
        for word in words:
            if word not in stop_words:
                clear_words.append(word)
        result.append(clear_words)
    return result

In [17]:
from nltk.corpus import stopwords
print(stopwords.words("english"))

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', 'too', 'very', 's', 't', 'can', 'will', 'just', 'don', "don't", 'should', "should've", 'now', 'd', 'll', 'm', 'o', 're', 've', 'y', 'ain', 'aren', "aren't", 'couldn', "couldn't", 'didn', "didn't", 'doesn', "doesn't", 'hadn', "hadn't", 'hasn', "hasn't", 'haven', "haven't", 'isn', "isn't", 'ma', 'mightn', "mightn't", 'mustn', "mustn't", 'needn', "needn't", 'shan', "shan't", 'shouldn', "shouldn't", 'wasn', "wasn't", 'weren', "weren't", 'won', "won't", 'wouldn', "wouldn't"]

In [18]:
from nltk.corpus import stopwords
print(stopwords.words("russian"))

['и', 'в', 'во', 'не', 'что', 'он', 'на', 'я', 'с', 'со', 'как', 'а', 'то', 'все', 'она', 'так', 'его', 'но', 'да', 'ты', 'к', 'у', 'же', 'вы', 'за', 'бы', 'по', 'только', 'ее', 'мне', 'было', 'вот', 'от', 'меня', 'еще', 'нет', 'о', 'из', 'ему', 'теперь', 'когда', 'даже', 'ну', 'вдруг', 'ли', 'если', 'уже', 'или', 'ни', 'быть', 'был', 'него', 'до', 'вас', 'нибудь', 'опять', 'уж', 'вам', 'ведь', 'там', 'потом', 'себя', 'ничего', 'ей', 'может', 'они', 'тут', 'где', 'есть', 'надо', 'ней', 'для', 'мы', 'тебя', 'их', 'чем', 'была', 'сам', 'чтоб', 'без', 'будто', 'чего', 'раз', 'тоже', 'себе', 'под', 'будет', 'ж', 'тогда', 'кто', 'этот', 'того', 'потому', 'этого', 'какой', 'совсем', 'ним', 'здесь', 'этом', 'один', 'почти', 'мой', 'тем', 'чтобы', 'нее', 'сейчас', 'были', 'куда', 'зачем', 'всех', 'никогда', 'можно', 'при', 'наконец', 'два', 'об', 'другой', 'хоть', 'после', 'над', 'больше', 'тот', 'через', 'эти', 'нас', 'про', 'всего', 'них', 'какая', 'много', 'разве', 'три', 'эту', 'моя', 'впрочем', 'хорошо', 'свою', 'этой', 'перед', 'иногда', 'лучше', 'чуть', 'том', 'нельзя', 'такой', 'им', 'более', 'всегда', 'конечно', 'всю', 'между']

In [19]:
from nltk.corpus import stopwords
print(stopwords.words("french"))

['au', 'aux', 'avec', 'ce', 'ces', 'dans', 'de', 'des', 'du', 'elle', 'en', 'et', 'eux', 'il', 'ils', 'je', 'la', 'le', 'les', 'leur', 'lui', 'ma', 'mais', 'me', 'même', 'mes', 'moi', 'mon', 'ne', 'nos', 'notre', 'nous', 'on', 'ou', 'par', 'pas', 'pour', 'qu', 'que', 'qui', 'sa', 'se', 'ses', 'son', 'sur', 'ta', 'te', 'tes', 'toi', 'ton', 'tu', 'un', 'une', 'vos', 'votre', 'vous', 'c', 'd', 'j', 'l', 'à', 'm', 'n', 's', 't', 'y', 'été', 'étée', 'étées', 'étés', 'étant', 'étante', 'étants', 'étantes', 'suis', 'es', 'est', 'sommes', 'êtes', 'sont', 'serai', 'seras', 'sera', 'serons', 'serez', 'seront', 'serais', 'serait', 'serions', 'seriez', 'seraient', 'étais', 'était', 'étions', 'étiez', 'étaient', 'fus', 'fut', 'fûmes', 'fûtes', 'furent', 'sois', 'soit', 'soyons', 'soyez', 'soient', 'fusse', 'fusses', 'fût', 'fussions', 'fussiez', 'fussent', 'ayant', 'ayante', 'ayantes', 'ayants', 'eu', 'eue', 'eues', 'eus', 'ai', 'as', 'avons', 'avez', 'ont', 'aurai', 'auras', 'aura', 'aurons', 'aurez', 'auront', 'aurais', 'aurait', 'aurions', 'auriez', 'auraient', 'avais', 'avait', 'avions', 'aviez', 'avaient', 'eut', 'eûmes', 'eûtes', 'eurent', 'aie', 'aies', 'ait', 'ayons', 'ayez', 'aient', 'eusse', 'eusses', 'eût', 'eussions', 'eussiez', 'eussent']

In [20]:
stop_words = set(stopwords.words("english"))
sentence = "Backgammon is one of the oldest known board games."

words = nltk.word_tokenize(sentence)
without_stop_words = [word for word in words if not word in stop_words]
print(without_stop_words)

['Backgammon', 'one', 'oldest', 'known', 'board', 'games', '.']

In [ ]:
# from nltk.corpus import stopwords  # стоп слова
# nltk.download('stopwords')

### Векторизация

In [ ]:
# df = pd.read_csv("data.csv.gz", compression='gzip')

In [21]:
# df = pd.read_csv('parsed_reviews3.csv', on_bad_lines='skip')
df = pd.read_csv('news_summary_more.csv', on_bad_lines='skip')

In [22]:
df = df[:100]

In [23]:
df

,headlines,text
0,upGrad learner switches to career in ML & Al w...,"Saurav Kant, an alumnus of upGrad and IIIT-B's..."
1,Delhi techie wins free food from Swiggy for on...,Kunal Shah's credit card bill payment platform...
2,New Zealand end Rohit Sharma-led India's 12-ma...,New Zealand defeated India by 8 wickets in the...
3,Aegon life iTerm insurance plan helps customer...,"With Aegon Life iTerm Insurance plan, customer..."
4,"Have known Hirani for yrs, what if MeToo claim...",Speaking about the sexual harassment allegatio...
...,...,...
95,Actress Patralekhaa to make her Kannada film d...,Actress Patralekhaa will make her debut in the...
96,"Gmail faces temporary global outage, users fac...","Gmail on Tuesday faced a global outage, which ..."
97,Decide about an alliance within 15 days: Uddha...,Shiv Sena chief Uddhav Thackeray has asked the...
98,"Grand alliance, if wins, will see a new PM eve...",BJP President Amit Shah on Wednesday took a di...
99,Demonetisation made homes affordable for youth...,Prime Minister Narendra Modi on Wednesday said...

#### Мешок слов

In [24]:
from sklearn.feature_extraction.text import CountVectorizer #, TfidfVectorizer

In [25]:
data = df.headlines.tolist() # приведение столбцы с body в список строк

In [26]:
data

['upGrad learner switches to career in ML & Al with 90% salary hike',
 'Delhi techie wins free food from Swiggy for one year on CRED',
 "New Zealand end Rohit Sharma-led India's 12-match winning streak",
 'Aegon life iTerm insurance plan helps customers save tax',
 'Have known Hirani for yrs, what if MeToo claims are not true: Sonam',
 'Rahat Fateh Ali Khan denies getting notice for smuggling currency',
 'India get all out for 92, their lowest ODI total in New Zealand',
 'Govt directs Alok Verma to join work 1 day before his retirement',
 "Called PM Modi 'sir' 10 times to satisfy his ego: Andhra CM",
 'Cong wins Ramgarh bypoll in Rajasthan, takes total to 100 seats',
 'UP cousins fed human excreta for friendship with boys',
 "81-yr-old woman conducts physical training in J'khand schools",
 "Ram, Krishna didn't smoke, why should we: Ramdev to sadhus at Kumbh",
 'Pharma exec gave doctor a lap dance to sell medicine in US: Witness',
 " I only cried at my 'bidaai' as I felt peer pressure: Isha Ambani",
 'Louis Vuitton owner to stockpile 4 months of wine, spirits in UK',
 'Karan Johar, Tabu turn showstoppers on opening night of LFW',
 'Those on bail will go to jail: PM Modi takes jibe at Rahul',
 "How long can I tolerate Congress leaders' potshots: K'taka CM",
 'Odisha CM Patnaik controls mining mafia: Union Minister',
 'I think the opposition even dreams about me: PM Modi',
 'ISRO unveils Bengaluru centre for manned space mission ',
 '12 killed, 170 injured in Saudi Arabia floods',
 'Isha Ambani features on February cover of Vogue magazine',
 'Indian Oil looking for annual deal to buy crude from US',
 'Pacer once took 7 wickets for just 1 run in 32 balls in a Test',
 "UK zoo offers people to name cockroach after their ex on Valentine's",
 'Rohit Sharma becomes 14th Indian cricketer to play 200 ODIs',
 "19-year-old Shubman Gill becomes India's 227th ODI cricketer",
 "2 seat cushions from 'missing plane carrying footballer' found",
 'Italian coach knocks rival down with headbutt, banned for 5 months',
 'Cyclists sleep on stadium floor instead of hotel over costly cycles',
 'Brazilian mother narrates football matches to blind son from stands',
 'SBI left account data of millions of users unprotected: Report',
 'CM Parrikar under pressure from PM after our Goa meet: Rahul',
 'Man arrested for cheating Amazon of â\x82¹30 lakh by taking refunds',
 'AgustaWestland scam accused Rajiv Saxena extradited to India',
 "Pakistan holds 'keys to war': Afghanistan",
 "Insurance agent 'Lord Voldemort' jailed for threatening clients",
 'Woman turns Apple AirPods into earrings to avoid losing them',
 "Shocked, hurt by ICICI's decision, truth will prevail: Kochhar",
 'Fashion brand H&M hires Facebook data scandal whistleblower',
 'Twitter testing news-first timeline feature on Android',
 "Samsung builds world's first 1TB storage chip for smartphones ",
 "People with 'negative mindset' quizzing pro-poor schemes: PM",
 'Rahul is hybrid specimen, has no clue about religion: Hegde',
 'Extreme cold to affect 200 million people as polar vortex hits US',
 "13 booked for firing air shots at Mahatma Gandhi's effigy",
 'Railway police rescues woman with leg stuck in train toilet',
 'US begins sending back asylum seekers to Mexico',
 'Yashwant Sinha demands probe into alleged fund diversion by DHFL',
 'Boeing sales cross $100bn for 1st time in its 102-yr history',
 'headlines',
 'OnePlus named bestselling premium smartphone brand of 2018: Report',
 'Can never look at female body, even if naked, in vulgar way: Pooja',
 "Kangana made fake promises to cast: 'Manikarnika' actress Mishti",
 'PM-led panel to meet on Friday to pick new CBI chief: Kharge',
 'McGregor fined â\x82¹35 lakh, Khabib â\x82¹3.5 crore for brawl; both banned',
 "Banned for 4 matches, Sarfaraz shares 'log hai na' poem for critics",
 'Confessed to spot-fixing to escape police torture: Sreesanth to SC',
 'Govt to present Interim Budget, not full Budget on February 1',
 'US intelligence naive and wrong, should go back to school: Trump',
 'Vatican priest handling sex abuse cases quits over alleged sex abuse',
 'Woman rejects job after CEO bullies her in interview; he apologises',
 'Police officer probing Paytm extortion case arrested for extortion',
 'Qatar to invest $200 million in Airtel Africa',
 'Rohit Shetty still working on script for Golmaal 5: Shreyas',
 'Man sues Avengers actress Gwyneth for â\x82¹22 crore over ski crash',
 "Yami Gautam felicitated by BSF for performance in 'Uri...'",
 'Facebook hires its privacy critic as privacy policy manager',
 "Apple to cut some iPhones' prices outside US over strong dollar",
 'Scientists test wetsuit to protect wearer after shark attack',
 "Come armed with sticks for PM Modi's rally in WB: BJP leader",
 "'4B' for Opposition is 'Bua-Bhatija-Bhai-Behen': Amit Shah",
 'Volkswagen retains top spot in global sales, beats Toyota',
 'Plot, treason by Nissan executives led to my arrest: Ghosn',
 'Govt cuts customs duty on electric vehicle parts to 10-15%',
 'Swine flu outbreak kills 76 in Rajasthan',
 'N Korea unlikely to give up nuclear weapons: US intelligence chief',
 'Jet Airways denies being told to ground aircraft',
 'ICICI fires Chanda Kochhar, to take back bonuses paid in last 9 yrs',
 'Ex-cricketer Martin out of ICU after being on ventilator for a month',
 "Malinga's wife targets Perera on Facebook, he seeks board's help",
 "Don't use visit to ailing man for political gains: Goa CM to Rahul",
 'PM Modi stops speech after cameraman faints, asks officers to help',
 'Couple divorces minutes after marriage as families fight over lunch',
 'Minister praises rape-convict Asaram over Matru-Pitru Divas',
 'Trump ordered to kill me: Venezuela President Maduro',
 '8 Asian billionaires aged over 90, including Mistry, control $125bn',
 '1,000 kg banned plastic seized from Saravana Bhavan in Chennai',
 'Shamita Shetty abused, driver slapped after accident: Report',
 'Trolling has become the norm on social media: Vaani',
 'Whoever invented marriage was creepy as hell: Sushmita posts joke',
 'Actor Karanvir Bohra detained in Russia over passport damage',
 "If I don't get an award, that award is at loss: SRK",
 'Actress Patralekhaa to make her Kannada film debut ',
 "Gmail faces temporary global outage, users face '404 error'",
 'Decide about an alliance within 15 days: Uddhav to BJP',
 'Grand alliance, if wins, will see a new PM every day: Shah',
 'Demonetisation made homes affordable for youth: PM Modi']

In [27]:
vectorizer = CountVectorizer(analyzer="word", max_features=1000, token_pattern="[a-z]+", lowercase=True, stop_words='english', ngram_range=(1,2))  # инициализация векторизатора

vectorizer.fit(data) # обучение векторизатора

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=1000, min_df=1,
                ngram_range=(1, 2), preprocessor=None, stop_words='english',
                strip_accents=None, token_pattern='[a-z]+', tokenizer=None,
                vocabulary=None)

In [28]:
sub_data = data[:10] # [:10] - срез

In [29]:
vectors = vectorizer.transform(sub_data)  # посчитаем полученные вектора для первых 10 строк

In [30]:
vectors.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 1, 1],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [31]:
vectors.toarray().shape

(10, 1000)

#### TF_IDF

In [32]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_vectorizer = TfidfVectorizer()
values = tfidf_vectorizer.fit_transform(data)

# Show the Model as a pandas DataFrame
feature_names = tfidf_vectorizer.get_feature_names()
pd.DataFrame(values.toarray(), columns = feature_names)

,000,10,100,100bn,102,12,125bn,13,14th,15,...,year,youth,yr,yrs,zealand,zoo,¹22,¹3,¹30,¹35
0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.00000,...,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.00000,...,0.294416,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.300462,0.0,0.0,0.0,0.00000,...,0.000000,0.000000,0.0,0.000000,0.300462,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.00000,...,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.00000,...,0.000000,0.000000,0.0,0.269705,0.000000,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.00000,...,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0
96,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.00000,...,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0
97,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.31896,...,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0
98,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.00000,...,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0
99,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.00000,...,0.000000,0.406412,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0

In [33]:
# ваш код здесь
tf_idfvectorizer = TfidfVectorizer(analyzer="word", max_features=1500, token_pattern="[a-z]+", lowercase=True)

In [34]:
tf_idfvectorizer.fit(data)

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.float64'>, encoding='utf-8',
                input='content', lowercase=True, max_df=1.0, max_features=1500,
                min_df=1, ngram_range=(1, 1), norm='l2', preprocessor=None,
                smooth_idf=True, stop_words=None, strip_accents=None,
                sublinear_tf=False, token_pattern='[a-z]+', tokenizer=None,
                use_idf=True, vocabulary=None)

In [35]:
vect = tf_idfvectorizer.transform(sub_data)

In [36]:
vect.shape

(10, 681)

In [37]:
vect.toarray()

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.30643121,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [38]:
# ??vect

#### Word2Vec

In [98]:
!pip install gensim

Requirement already satisfied: gensim in c:\programdata\anaconda3\lib\site-packages (4.2.0)
Requirement already satisfied: numpy>=1.17.0 in c:\programdata\anaconda3\lib\site-packages (from gensim) (1.21.6)
Requirement already satisfied: scipy>=0.18.1 in c:\programdata\anaconda3\lib\site-packages (from gensim) (1.3.1)
Requirement already satisfied: smart-open>=1.8.1 in c:\programdata\anaconda3\lib\site-packages (from gensim) (6.4.0)
Requirement already satisfied: Cython==0.29.28 in c:\programdata\anaconda3\lib\site-packages (from gensim) (0.29.28)

WARNING: Ignoring invalid distribution -umpy (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -yping-extensions (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -yping-extensions (c:\programdata\anaconda3\lib\site-packages)

In [39]:
from gensim.models.word2vec import Word2Vec  # подключение модели word2vec
from tqdm.notebook import tqdm  # подключения библиотеки прогресс бара

In [40]:
def get_wv_data(data):
    wv_data = []
    for s in tqdm(data):
        lst = re.findall("[a-z]+", s.lower())
        wv_data.append(lst)
    return wv_data

In [41]:
wv_data = get_wv_data(df.text.to_list())

  0%|          | 0/100 [00:00<?, ?it/s]

In [42]:
wv_data

[['saurav',
  'kant',
  'an',
  'alumnus',
  'of',
  'upgrad',
  'and',
  'iiit',
  'b',
  's',
  'pg',
  'program',
  'in',
  'machine',
  'learning',
  'and',
  'artificial',
  'intelligence',
  'was',
  'a',
  'sr',
  'systems',
  'engineer',
  'at',
  'infosys',
  'with',
  'almost',
  'years',
  'of',
  'work',
  'experience',
  'the',
  'program',
  'and',
  'upgrad',
  's',
  'degree',
  'career',
  'support',
  'helped',
  'him',
  'transition',
  'to',
  'a',
  'data',
  'scientist',
  'at',
  'tech',
  'mahindra',
  'with',
  'salary',
  'hike',
  'upgrad',
  's',
  'online',
  'power',
  'learning',
  'has',
  'powered',
  'lakh',
  'careers'],
 ['kunal',
  'shah',
  's',
  'credit',
  'card',
  'bill',
  'payment',
  'platform',
  'cred',
  'gave',
  'users',
  'a',
  'chance',
  'to',
  'win',
  'free',
  'food',
  'from',
  'swiggy',
  'for',
  'one',
  'year',
  'pranav',
  'kaushik',
  'a',
  'delhi',
  'techie',
  'bagged',
  'this',
  'reward',
  'after',
  'spending',
  'cred',
  'coins',
  'users',
  'get',
  'one',
  'cred',
  'coin',
  'per',
  'rupee',
  'of',
  'bill',
  'paid',
  'which',
  'can',
  'be',
  'used',
  'to',
  'avail',
  'rewards',
  'from',
  'brands',
  'like',
  'ixigo',
  'bookmyshow',
  'ubereats',
  'cult',
  'fit',
  'and',
  'more'],
 ['new',
  'zealand',
  'defeated',
  'india',
  'by',
  'wickets',
  'in',
  'the',
  'fourth',
  'odi',
  'at',
  'hamilton',
  'on',
  'thursday',
  'to',
  'win',
  'their',
  'first',
  'match',
  'of',
  'the',
  'five',
  'match',
  'odi',
  'series',
  'india',
  'lost',
  'an',
  'international',
  'match',
  'under',
  'rohit',
  'sharma',
  's',
  'captaincy',
  'after',
  'consecutive',
  'victories',
  'dating',
  'back',
  'to',
  'march',
  'the',
  'match',
  'witnessed',
  'india',
  'getting',
  'all',
  'out',
  'for',
  'their',
  'seventh',
  'lowest',
  'total',
  'in',
  'odi',
  'cricket',
  'history'],
 ['with',
  'aegon',
  'life',
  'iterm',
  'insurance',
  'plan',
  'customers',
  'can',
  'enjoy',
  'tax',
  'benefits',
  'on',
  'your',
  'premiums',
  'paid',
  'and',
  'save',
  'up',
  'to',
  'on',
  'taxes',
  'the',
  'plan',
  'provides',
  'life',
  'cover',
  'up',
  'to',
  'the',
  'age',
  'of',
  'years',
  'also',
  'customers',
  'have',
  'options',
  'to',
  'insure',
  'against',
  'critical',
  'illnesses',
  'disability',
  'and',
  'accidental',
  'death',
  'benefit',
  'rider',
  'with',
  'a',
  'life',
  'cover',
  'up',
  'to',
  'the',
  'age',
  'of',
  'years'],
 ['speaking',
  'about',
  'the',
  'sexual',
  'harassment',
  'allegations',
  'against',
  'rajkumar',
  'hirani',
  'sonam',
  'kapoor',
  'said',
  'i',
  've',
  'known',
  'hirani',
  'for',
  'many',
  'years',
  'what',
  'if',
  'it',
  's',
  'not',
  'true',
  'the',
  'metoo',
  'movement',
  'will',
  'get',
  'derailed',
  'in',
  'the',
  'metoo',
  'movement',
  'i',
  'always',
  'believe',
  'a',
  'woman',
  'but',
  'in',
  'this',
  'case',
  'we',
  'need',
  'to',
  'reserve',
  'our',
  'judgment',
  'she',
  'added',
  'hirani',
  'has',
  'been',
  'accused',
  'by',
  'an',
  'assistant',
  'who',
  'worked',
  'in',
  'sanju'],
 ['pakistani',
  'singer',
  'rahat',
  'fateh',
  'ali',
  'khan',
  'has',
  'denied',
  'receiving',
  'any',
  'notice',
  'from',
  'the',
  'enforcement',
  'directorate',
  'over',
  'allegedly',
  'smuggling',
  'foreign',
  'currency',
  'out',
  'of',
  'india',
  'it',
  'would',
  'have',
  'been',
  'better',
  'if',
  'the',
  'authorities',
  'would',
  'have',
  'served',
  'the',
  'notice',
  'first',
  'if',
  'any',
  'and',
  'then',
  'publicised',
  'this',
  'reads',
  'a',
  'press',
  'release',
  'issued',
  'on',
  'behalf',
  'of',
  'rahat',
  'the',
  'statement',
  'further',
  'called',
  'the',
  'allegation',
  'bizarre'],
 ['india',
  'recorded',
  'their',
  'lowest',
  'odi',
  'total',
  'in',
  'new',
  'zealand',
  'after',
  'getting',
  'all',
  'out',
  'for',
  'runs',
  'in',
  'overs',
  'in',
  'the',
  'fourth',
  'odi',
  'at',
  'hamilton',
  'on',
  'thursday',
  'seven',
  'of',
  'india',
  's',
  'batsmen',
  'were',
  'dismissed',
  'for',
  'single',
  'digit',
  'scores',
  'while',
  'their',
  'number',
  'ten',
  'batsman',
  'yuzvendra',
  'chahal',
  'top',
  'scored',
  'with',
  'india',
  's',
  'previous',
  'lowest',
  'odi',
  'total',
  'in',
  'new',
  'zealand',
  'was'],
 ['weeks',
  'after',
  'ex',
  'cbi',
  'director',
  'alok',
  'verma',
  'told',
  'the',
  'department',
  'of',
  'personnel',
  'and',
  'training',
  'to',
  'consider',
  'him',
  'retired',
  'the',
  'home',
  'ministry',
  'asked',
  'him',
  'to',
  'join',
  'work',
  'on',
  'the',
  'last',
  'day',
  'of',
  'his',
  'fixed',
  'tenure',
  'as',
  'director',
  'on',
  'thursday',
  'the',
  'ministry',
  'directed',
  'him',
  'to',
  'immediately',
  'join',
  'as',
  'dg',
  'fire',
  'services',
  'the',
  'post',
  'he',
  'was',
  'transferred',
  'to',
  'after',
  'his',
  'removal',
  'as',
  'cbi',
  'chief'],
 ['andhra',
  'pradesh',
  'cm',
  'n',
  'chandrababu',
  'naidu',
  'has',
  'said',
  'when',
  'i',
  'met',
  'then',
  'us',
  'president',
  'bill',
  'clinton',
  'i',
  'addressed',
  'him',
  'as',
  'mr',
  'clinton',
  'not',
  'as',
  'sir',
  'pm',
  'narendra',
  'modi',
  'is',
  'my',
  'junior',
  'in',
  'politics',
  'i',
  'addressed',
  'him',
  'as',
  'sir',
  'times',
  'i',
  'did',
  'this',
  'to',
  'satisfy',
  'his',
  'ego',
  'in',
  'the',
  'hope',
  'that',
  'he',
  'will',
  'do',
  'justice',
  'to',
  'the',
  'state',
  'he',
  'added'],
 ['congress',
  'candidate',
  'shafia',
  'zubair',
  'won',
  'the',
  'ramgarh',
  'assembly',
  'seat',
  'in',
  'rajasthan',
  'by',
  'defeating',
  'bjp',
  's',
  'sukhwant',
  'singh',
  'with',
  'a',
  'margin',
  'of',
  'votes',
  'in',
  'the',
  'bypoll',
  'with',
  'this',
  'victory',
  'congress',
  'has',
  'taken',
  'its',
  'total',
  'to',
  'seats',
  'in',
  'the',
  'member',
  'assembly',
  'the',
  'election',
  'to',
  'the',
  'ramgarh',
  'seat',
  'was',
  'delayed',
  'due',
  'to',
  'the',
  'death',
  'of',
  'sitting',
  'mla',
  'and',
  'bsp',
  'candidate',
  'laxman',
  'singh'],
 ['two',
  'minor',
  'cousins',
  'in',
  'uttar',
  'pradesh',
  's',
  'gorakhpur',
  'were',
  'allegedly',
  'repeatedly',
  'burnt',
  'with',
  'tongs',
  'and',
  'forced',
  'to',
  'eat',
  'human',
  'excreta',
  'by',
  'their',
  'family',
  'for',
  'being',
  'friends',
  'with',
  'two',
  'boys',
  'from',
  'the',
  'same',
  'school',
  'the',
  'cousins',
  'revealed',
  'their',
  'ordeal',
  'to',
  'the',
  'police',
  'and',
  'child',
  'welfare',
  'committee',
  'after',
  'being',
  'brought',
  'back',
  'to',
  'gorakhpur',
  'from',
  'nepal',
  'where',
  'they',
  'had',
  'fled',
  'to',
  'escape',
  'the',
  'torture'],
 ['isha',
  'ghosh',
  'an',
  'year',
  'old',
  'member',
  'of',
  'bharat',
  'scouts',
  'and',
  'guides',
  'bsg',
  'has',
  'been',
  'imparting',
  'physical',
  'and',
  'mental',
  'training',
  'to',
  'schoolchildren',
  'in',
  'jharkhand',
  'for',
  'several',
  'decades',
  'chaibasa',
  'based',
  'ghosh',
  'reportedly',
  'walks',
  'seven',
  'kilometres',
  'daily',
  'and',
  'spends',
  'eight',
  'hours',
  'conducting',
  'physical',
  'training',
  'apart',
  'from',
  'climbing',
  'and',
  'yoga',
  'sessions',
  'she',
  'says',
  'one',
  'should',
  'do',
  'something',
  'for',
  'society',
  'till',
  'one',
  's',
  'last',
  'breath'],
 ['urging',
  'saints',
  'and',
  'seers',
  'at',
  'the',
  'kumbh',
  'mela',
  'to',
  'quit',
  'smoking',
  'yoga',
  'guru',
  'ramdev',
  'said',
  'we',
  'follow',
  'ram',
  'and',
  'krishna',
  'who',
  'never',
  'smoked',
  'in',
  'their',
  'life',
  'then',
  'why',
  'should',
  'we',
  'making',
  'them',
  'take',
  'a',
  'pledge',
  'to',
  'quit',
  'tobacco',
  'he',
  'collected',
  'chillum',
  'clay',
  'pipe',
  'from',
  'several',
  'sadhus',
  'he',
  'said',
  'he',
  'will',
  'deposit',
  'the',
  'chillums',
  'for',
  'display',
  'at',
  'a',
  'museum',
  'he',
  'll',
  'build'],
 ['former',
  'stripper',
  'and',
  'regional',
  'sales',
  'director',
  'of',
  'a',
  'pharmaceutical',
  'company',
  'sunrise',
  'lee',
  'gave',
  'a',
  'doctor',
  'a',
  'lap',
  'dance',
  'in',
  'a',
  'nightclub',
  'to',
  'persuade',
  'him',
  'to',
  'prescribe',
  'an',
  'addictive',
  'fentanyl',
  'spray',
  'in',
  'the',
  'company',
  's',
  'sales',
  'representative',
  'told',
  'a',
  'us',
  'court',
  'she',
  'said',
  'she',
  'saw',
  'lee',
  'sitting',
  'on',
  'doctor',
  's',
  'lap',
  'kind',
  'of',
  'bouncing',
  'around',
  'lee',
  'has',
  'been',
  'accused',
  'of',
  'bribing',
  'doctors'],
 ['reliance',
  'industries',
  'chairman',
  'mukesh',
  'ambani',
  's',
  'daughter',
  'isha',
  'ambani',
  'who',
  'got',
  'married',
  'last',
  'month',
  'said',
  'she',
  'only',
  'cried',
  'at',
  'her',
  'bidaai',
  'because',
  'she',
  'felt',
  'peer',
  'pressure',
  'as',
  'everyone',
  'was',
  'crying',
  'especially',
  'her',
  'parents',
  'i',
  'was',
  'emotional',
  'too',
  'but',
  'everyone',
  'around',
  'me',
  'would',
  'cry',
  'all',
  'the',
  'time',
  'she',
  'added',
  'it',
  'was',
  'a',
  'very',
  'emotional',
  'affair',
  'for',
  'everyone',
  'in',
  'my',
  'family',
  'said',
  'isha'],
 ['louis',
  'vuitton',
  'owner',
  'lvmh',
  'which',
  'makes',
  'high',
  'end',
  'beverages',
  'like',
  'mo',
  't',
  'chandon',
  'champagne',
  'and',
  'hennessy',
  'cognac',
  'said',
  'it',
  's',
  'stockpiling',
  'four',
  'months',
  'worth',
  'of',
  'wine',
  'and',
  'spirits',
  'in',
  'uk',
  'in',
  'preparation',
  'for',
  'brexit',
  'we',
  're',
  'ready',
  'for',
  'worst',
  'case',
  'scenario',
  'if',
  'there',
  'are',
  'difficulties',
  'with',
  'deliveries',
  'the',
  'french',
  'luxury',
  'giant',
  'said',
  'the',
  'uk',
  'is',
  'scheduled',
  'to',
  'leave',
  'the',
  'eu',
  'on',
  'march'],
 ['filmmaker',
  'karan',
  'johar',
  'and',
  'actress',
  'tabu',
  'turned',
  'showstoppers',
  'for',
  'gaurav',
  'gupta',
  'on',
  'the',
  'opening',
  'night',
  'of',
  'lakm',
  'fashion',
  'week',
  'summer',
  'resort',
  'while',
  'johar',
  'wore',
  'a',
  'red',
  'sequinned',
  'jacket',
  'with',
  'black',
  'pants',
  'tabu',
  'walked',
  'the',
  'ramp',
  'in',
  'a',
  'grey',
  'embellished',
  'gown',
  'the',
  'fashion',
  'show',
  'which',
  'began',
  'on',
  'january',
  'will',
  'continue',
  'till',
  'february'],
 ['in',
  'a',
  'jibe',
  'at',
  'congress',
  'president',
  'rahul',
  'gandhi',
  'pm',
  'narendra',
  'modi',
  'on',
  'wednesday',
  'said',
  'those',
  'on',
  'bail',
  'will',
  'have',
  'to',
  'go',
  'to',
  'jail',
  'pm',
  'modi',
  'added',
  'he',
  'is',
  'out',
  'on',
  'bail',
  'and',
  'his',
  'associates',
  'too',
  'are',
  'facing',
  'charges',
  'i',
  'know',
  'they',
  'will',
  'be',
  'convicted',
  'one',
  'day',
  'the',
  'pm',
  'claimed',
  'he',
  'd',
  'waged',
  'a',
  'war',
  'on',
  'corruption',
  'because',
  'he',
  's',
  'from',
  'a',
  'common',
  'household'],
 ['days',
  'after',
  'he',
  'threatened',
  'to',
  'step',
  'down',
  'from',
  'his',
  'post',
  'if',
  'congress',
  'mlas',
  'continue',
  'crossing',
  'the',
  'line',
  'karnataka',
  'chief',
  'minister',
  'hd',
  'kumaraswamy',
  'accused',
  'them',
  'of',
  'taking',
  'potshots',
  'and',
  'asked',
  'how',
  'many',
  'more',
  'days',
  'can',
  'i',
  'tolerate',
  'such',
  'stuff',
  'kumaraswamy',
  'who',
  'made',
  'the',
  'statements',
  'after',
  'a',
  'congress',
  'mla',
  'demanded',
  'that',
  'siddaramaiah',
  'be',
  'made',
  'cm',
  'again',
  'said',
  'power',
  'is',
  'ephemeral'],
 ['union',
  'minister',
  'dharmendra',
  'pradhan',
  'on',
  'wednesday',
  'claimed',
  'the',
  'illegal',
  'mining',
  'mafia',
  'in',
  'odisha',
  'operates',
  'under',
  'the',
  'control',
  'of',
  'cm',
  'naveen',
  'patnaik',
  'and',
  'state',
  'congress',
  'chief',
  'niranjan',
  'patnaik',
  'he',
  'added',
  'the',
  'time',
  'has',
  'come',
  'for',
  'the',
  'people',
  'of',
  'odisha',
  'to',
  'put',
  'a',
  'full',
  'stop',
  'to',
  'their',
  'activities',
  'the',
  'time',
  'has',
  'come',
  'for',
  'us',
  'to',
  'ask',
  'for',
  'an',
  'explanation',
  'from',
  'this',
  'corrupt',
  'government'],
 ['claiming',
  'there',
  'is',
  'a',
  'dearth',
  'of',
  'ideas',
  'among',
  'opposition',
  'parties',
  'prime',
  'minister',
  'narendra',
  'modi',
  'on',
  'wednesday',
  'said',
  'the',
  'opposition',
  'talks',
  'only',
  'about',
  'modi',
  'the',
  'whole',
  'day',
  'i',
  'suspect',
  'they',
  'even',
  'dream',
  'about',
  'me',
  'pm',
  'modi',
  'who',
  'was',
  'addressing',
  'the',
  'new',
  'india',
  'youth',
  'conclave',
  'in',
  'surat',
  'added',
  'that',
  'the',
  'opposition',
  'parties',
  'have',
  'only',
  'one',
  'agenda',
  'which',
  'is',
  'modi'],
 ['the',
  'indian',
  'space',
  'research',
  'organisation',
  'on',
  'wednesday',
  'unveiled',
  'human',
  'space',
  'flight',
  'centre',
  'in',
  'bengaluru',
  'for',
  'its',
  'crore',
  'manned',
  'space',
  'mission',
  'gaganyaan',
  'scheduled',
  'for',
  'isro',
  'said',
  'the',
  'centre',
  'will',
  'be',
  'responsible',
  'for',
  'development',
  'of',
  'engineering',
  'systems',
  'for',
  'crew',
  'survival',
  'in',
  'space',
  'and',
  'crew',
  'selection',
  'and',
  'training',
  'it',
  'll',
  'also',
  'pursue',
  'activities',
  'for',
  'sustained',
  'human',
  'space',
  'flight',
  'missions',
  'isro',
  'added'],
 ['at',
  'least',
  'people',
  'have',
  'been',
  'killed',
  'and',
  'others',
  'have',
  'been',
  'injured',
  'in',
  'saudi',
  'arabia',
  'this',
  'week',
  'due',
  'to',
  'flooding',
  'from',
  'heavy',
  'rain',
  'the',
  'emergency',
  'services',
  'rescued',
  'people',
  'from',
  'the',
  'flooded',
  'areas',
  'more',
  'than',
  'half',
  'of',
  'them',
  'in',
  'tabuk',
  'heavy',
  'rains',
  'hit',
  'mainly',
  'western',
  'and',
  'northwestern',
  'parts',
  'of',
  'saudi',
  'arabia',
  'near',
  'its',
  'border',
  'with',
  'jordan'],
 ['reliance',
  'industries',
  'chairman',
  'mukesh',
  'ambani',
  's',
  'daughter',
  'isha',
  'ambani',
  'has',
  'featured',
  'on',
  'the',
  'cover',
  'of',
  'the',
  'february',
  'edition',
  'of',
  'vogue',
  'india',
  'she',
  's',
  'dressed',
  'in',
  'a',
  'white',
  'shirt',
  'dress',
  'and',
  'black',
  'ruffled',
  'skirt',
  'by',
  'australian',
  'designer',
  'toni',
  'maticevski',
  'while',
  'accessorising',
  'her',
  'look',
  'with',
  'a',
  'misho',
  'ring',
  'in',
  'the',
  'cover',
  'story',
  'on',
  'her',
  'isha',
  'has',
  'spoken',
  'about',
  'her',
  'work',
  'and',
  'life',
  'after',
  'marriage'],
 ['indian',
  'oil',
  'corporation',
  'on',
  'wednesday',
  'said',
  'it',
  's',
  'looking',
  'for',
  'an',
  'annual',
  'deal',
  'to',
  'buy',
  'us',
  'crude',
  'as',
  'it',
  'seeks',
  'to',
  'broaden',
  'oil',
  'purchasing',
  'options',
  'this',
  'comes',
  'amid',
  'uncertainties',
  'over',
  'iran',
  'imports',
  'the',
  'us',
  'had',
  'in',
  'november',
  'granted',
  'a',
  'six',
  'month',
  'waiver',
  'to',
  'india',
  'from',
  'sanctions',
  'against',
  'iran',
  'and',
  'restricted',
  'the',
  'country',
  's',
  'monthly',
  'intake',
  'of',
  'iranian',
  'oil',
  'to',
  'barrels',
  'per',
  'day'],
 ['former',
  'windies',
  'fast',
  'bowler',
  'curtly',
  'ambrose',
  'dismissed',
  'seven',
  'australian',
  'batsmen',
  'within',
  'a',
  'span',
  'of',
  'balls',
  'giving',
  'away',
  'just',
  'one',
  'run',
  'in',
  'a',
  'test',
  'match',
  'on',
  'january',
  'ambrose',
  's',
  'spell',
  'helped',
  'his',
  'team',
  'bowl',
  'out',
  'australia',
  'for',
  'in',
  'the',
  'first',
  'innings',
  'after',
  'being',
  'for',
  'at',
  'one',
  'point',
  'ambrose',
  'ended',
  'with',
  'first',
  'innings',
  'figures',
  'of'],
 ['a',
  'london',
  'zoo',
  'is',
  'offering',
  'people',
  'to',
  'name',
  'a',
  'cockroach',
  'after',
  'their',
  'exes',
  'on',
  'valentine',
  's',
  'day',
  'for',
  'nearly',
  'for',
  'those',
  'that',
  'don',
  't',
  'quite',
  'require',
  'revenge',
  'there',
  's',
  'another',
  'way',
  'to',
  'make',
  'you',
  'feel',
  'better',
  'about',
  'getting',
  'back',
  'at',
  'your',
  'ex',
  'the',
  'zoo',
  'said',
  'in',
  'a',
  'statement',
  'the',
  'names',
  'will',
  'appear',
  'on',
  'zoo',
  's',
  'roach',
  'board',
  'on',
  'february'],
 ['stand',
  'in',
  'captain',
  'rohit',
  'sharma',
  'has',
  'become',
  'the',
  'th',
  'indian',
  'cricketer',
  'to',
  'play',
  'odis',
  'achieving',
  'the',
  'feat',
  'after',
  'taking',
  'the',
  'field',
  'against',
  'new',
  'zealand',
  'in',
  'fourth',
  'odi',
  'at',
  'hamilton',
  'on',
  'thursday',
  'the',
  'year',
  'old',
  'had',
  'made',
  'his',
  'odi',
  'debut',
  'on',
  'june',
  'against',
  'ireland',
  'in',
  'belfast',
  'rohit',
  'scored',
  'runs',
  'in',
  'his',
  'first',
  'odis',
  'at',
  'an',
  'average',
  'of'],
 ['batsman',
  'shubman',
  'gill',
  'has',
  'become',
  'the',
  'th',
  'cricketer',
  'to',
  'represent',
  'india',
  'in',
  'odi',
  'cricket',
  'achieving',
  'the',
  'feat',
  'against',
  'new',
  'zealand',
  'in',
  'the',
  'fourth',
  'odi',
  'at',
  'hamilton',
  'on',
  'thursday',
  'the',
  'year',
  'old',
  'received',
  'his',
  'maiden',
  'odi',
  'cap',
  'from',
  'former',
  'captain',
  'ms',
  'dhoni',
  'notably',
  'shubman',
  'was',
  'named',
  'player',
  'of',
  'the',
  'under',
  'world',
  'cup',
  'in',
  'new',
  'zealand',
  'last',
  'year'],
 ['investigators',
  'searching',
  'for',
  'a',
  'lost',
  'plane',
  'carrying',
  'argentine',
  'forward',
  'emiliano',
  'sala',
  'found',
  'two',
  'seat',
  'cushions',
  'on',
  'french',
  'coast',
  'that',
  'likely',
  'belonged',
  'to',
  'the',
  'aircraft',
  'the',
  'investigators',
  'said',
  'they',
  'll',
  'now',
  'launch',
  'an',
  'underwater',
  'seabed',
  'search',
  'for',
  'aircraft',
  'wreckage',
  'the',
  'cardiff',
  'city',
  'footballer',
  'was',
  'travelling',
  'from',
  'france',
  's',
  'nantes',
  'to',
  'wales',
  'cardiff',
  'when',
  'his',
  'plane',
  'disappeared',
  'over',
  'english',
  'channel',
  'on',
  'january'],
 ['italian',
  'third',
  'division',
  'football',
  'side',
  'lucchese',
  's',
  'head',
  'coach',
  'giancarlo',
  'favarin',
  'has',
  'been',
  'banned',
  'for',
  'five',
  'months',
  'for',
  'headbutting',
  'alessandria',
  's',
  'assistant',
  'coach',
  'gaetano',
  'mancino',
  'during',
  'a',
  'brawl',
  'following',
  'the',
  'teams',
  'draw',
  'on',
  'sunday',
  'mancino',
  'was',
  'caught',
  'off',
  'balance',
  'and',
  'knocked',
  'to',
  'the',
  'ground',
  'after',
  'the',
  'headbutt',
  'earlier',
  'in',
  'the',
  'match',
  'favarin',
  'had',
  'told',
  'his',
  'own',
  'player',
  'to',
  'break',
  'an',
  'opponent',
  's',
  'legs'],
 ['cyclists',
  'taking',
  'part',
  'in',
  'national',
  'track',
  'cycling',
  'championship',
  'in',
  'jaipur',
  'opted',
  'to',
  'sleep',
  'on',
  'the',
  'floor',
  'inside',
  'the',
  'stadium',
  'instead',
  'of',
  'hotels',
  'over',
  'expensive',
  'cycles',
  'the',
  'organisers',
  'had',

In [43]:
wv_model = Word2Vec(vector_size=100, window=5, min_count=10, negative=10, seed=42)  # инициализация модели
wv_model.build_vocab(wv_data)  # сбор словаря

In [44]:
wv_model.train(wv_data, total_examples=wv_model.corpus_count, epochs=5) # Обучение модели

(3791, 29675)

In [117]:
??wv_model

In [45]:
wv_model.wv.most_similar("it")

[('said', 0.9994866847991943),
 ('the', 0.9994863271713257),
 ('to', 0.999484658241272),
 ('added', 0.9994465112686157),
 ('of', 0.99942547082901),
 ('in', 0.9994018077850342),
 ('he', 0.9994006156921387),
 ('on', 0.9993842244148254),
 ('s', 0.9993510842323303),
 ('a', 0.9993345141410828)]

## Лабораторная работа

In [ ]:
1) Взять свой готовый датасет с отзывами (я пришлю)
2) Постройте два пайплайна лдя отображения текста в векторное пространство, используя либо Мешок слов/ngram/tf-idf, а также для построения вложений слов в данных отзывах (Word2Vec). Первый пайплайн без препроцессинга (удаление стоп-слов, лемматизация/стемминг), второй с ним.
3) Данные пайплайны оформите в виде класса. Для пайплайна с препроцессингом отдельно выделите методы токенизации, удаление стоп-слов, лемматизация/стемминг.

In [ ]:
class Preprocess_bad:
    def tf_idf():
        return
    
    def w2v():
    
class Preprocess_good:
    
    def stop_words():
        return
    
    def lemmatization():
        return
        
    def token():
        return
    
    def tf_idf():
        return
    
    def w2v():

In [3]:
df = pd.read_csv("data.csv.gz", compression='gzip')

In [4]:
df

,body,title,rating,bank_name,date
0,&lt;p&gt;Добрый день&lt;/p&gt;\r\n&lt;p&gt;пиш...,Заблокировали средства,1,Еком Банк,2023-01-03 12:46:11
1,&lt;p&gt;При возврате просроченной задолженнос...,Возврат просроченной задолженномти,1,Тинькофф Банк,2023-01-03 12:31:46
2,&lt;p&gt;07.09.22 ю была оформлена кредитная к...,"Ошибочное начисление комиссии, затягивание про...",1,Банк Открытие,2023-01-03 12:23:11
3,&lt;p&gt;Новый год начинается с приятностей)&l...,Клиентоориентиванность 10 из 10,5,Тинькофф Банк,2023-01-03 12:16:07
4,&lt;p&gt;Увидела на сайте Газпромбанка акцию с...,Как Газпромбанк обманывает клиентов с акционны...,1,Газпромбанк,2023-01-03 12:12:36
...,...,...,...,...,...
92730,"30 августа обнаружила, что баланс уменьшился. ...",Банк списал деньги и теперь рекомендует их сам...,1,Совкомбанк,2022-09-02 11:47:44
92731,Обратился с вопросом (6908609) по All Airlines...,Отличная консультация от сотрудника поддержки,5,Тинькофф Банк,2022-09-02 11:46:24
92732,В августе 2021 я досрочно погасил ипотеку (кре...,Снятие обременения с квартиры,2,Россельхозбанк,2022-09-02 11:34:34
92733,9.08.22 оформлен кредит на покупку автомобиля ...,Штрафные санкции,1,Драйв Клик Банк,2022-09-02 11:28:32
92734,Хочется выразить благодарность всему коллектив...,Рекомендуемый мной банк,5,Точка,2022-09-02 11:28:11